# Generated by Django 3.2.16 on 2023-01-18 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-deadline']},
        ),
        migrations.AddField(
            model_name='task',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 6, 40, 0, 772082)),
        ),
    ]
