# Generated by Django 3.2.16 on 2023-01-18 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230118_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 6, 52, 18, 230550)),
        ),
    ]
