# Generated by Django 3.2.16 on 2023-01-18 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2023, 1, 18, 6, 53, 16, 181623)),
        ),
    ]
