# Generated by Django 3.2.16 on 2023-01-25 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_task_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
        migrations.AlterField(
            model_name='task',
            name='timestamp',
            field=models.DateField(default=datetime.datetime(2023, 1, 25, 11, 19, 21, 645061)),
        ),
    ]
